name: Test Django Basic With Env

on:
#  workflow-dispatch:
#  schedule:
#    - cron: '30 15 * * * '
  push:
    branch:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
#    env:
#      DJANGO_SECRET_KEY: not-good
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Up Django Secret Key
        run: |
          my_key = $(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$my_key" >> $GITHUB_ENV

      - name: Install Requirements
#        working-directory: ./
        run: | 
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt

      - name: Django Tests
        working-directory: ./
        run: |
          python manage.py test
